In [10]:
import warnings

warnings.filterwarnings('ignore')

In [11]:
from sdv.datasets.demo import download_demo
from sdv.single_table import GaussianCopulaSynthesizer

real_data, metadata = download_demo(
  'single_table', 'fake_hotel_guests')

synthesizer = GaussianCopulaSynthesizer(metadata, locales=['es-MX'])
synthesizer.fit(real_data)

synthetic_data = synthesizer.sample(num_rows=100)

synthetic_data

,guest_email,has_rewards,room_type,amenities_fee,checkin_date,checkout_date,room_rate,billing_address,credit_card_number
0,tpalacios@example.org,False,BASIC,0.29,27 Mar 2020,09 Mar 2020,135.15,Ampliación Campeche 691 Interior 527\nVieja Ch...,5161033759518983
1,gabriela59@example.org,False,DELUXE,8.15,07 Sep 2020,25 Jun 2020,183.24,Boulevard Bosnia y Herzegovina 223 Interior 58...,4133047413145475690
2,bernardo15@example.net,False,BASIC,11.65,22 Mar 2020,01 Apr 2020,163.57,"Callejón Alonzo 689 Edif. 358 , Depto. 906\nNu...",4977328103788
3,rolondulce-maria@example.net,False,BASIC,48.12,04 Jun 2020,14 May 2020,127.75,Avenida Chad 690 Interior 651\nSan Espartaco l...,3524946844839485
4,rolandoquintanilla@example.org,False,DELUXE,11.07,08 Jan 2020,13 Jan 2020,180.12,Boulevard Villanueva 479 Interior 992\nNueva R...,4446905799576890978
...,...,...,...,...,...,...,...,...,...
95,davidporras@example.com,True,DELUXE,0.19,20 Jun 2020,06 Aug 2020,99.46,"Corredor Oaxaca 166 449\nVieja Somalia, MEX 45...",370346538790667
96,kvanegas@example.org,False,BASIC,15.45,28 Oct 2020,07 Nov 2020,234.53,Privada Nuevo León 503 Interior 026\nSan Herná...,503839312066
97,nacosta@example.com,False,BASIC,48.12,02 Mar 2020,14 Apr 2020,93.62,"Corredor Norte Pacheco 579 Edif. 838 , Depto. ...",4045519176177036
98,cbermudez@example.com,False,BASIC,10.82,20 Dec 2020,11 Dec 2020,240.35,Retorno Sur Reynoso 170 160\nSan Adela los alt...,566554083360
99,zoquendo@example.com,False,BASIC,8.36,27 May 2020,03 Apr 2020,93.29,"Eje vial Campeche 860 Edif. 476 , Depto. 466\n...",3543464185103468

In [14]:
from sdv.datasets.demo import get_available_demos

get_available_demos(modality='single_table')

                        dataset_name  size_MB  num_tables
0                              adult   20.848           1
1                              alarm   33.428           1
2                               asia    9.473           1
3                             census  647.349           1
4                    census_extended   29.077           1
5                              child   24.462           1
6                            covtype  255.645           1
7                 expedia_hotel_logs    0.444           1
8                     fake_companies    0.002           1
9                  fake_hotel_guests    0.201           1
10                         insurance   24.820           1
11                         intrusion  266.086           1
12  multiselectquestion_demo_dataset    6.002           1
13                              news   18.712           1
14          null_values_demo_dataset    1.361           1
15                student_placements    0.094           1
16            student_placements_pii    0.116           1

In [ ]:
from sdv.single_table import CTGANSynthesizer

real_data, metadata = download_demo(
  'single_table', 'adult')

synthesizer = CTGANSynthesizer(metadata, locales=['es-MX', 'en-US'])
synthesizer.fit(real_data)

synthetic_data = synthesizer.sample(num_rows=100)

synthetic_data

# took ~21 mins 34 s

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,label
0,31,Local-gov,146594,Some-college,10,Widowed,Adm-clerical,Not-in-family,White,Female,13,0,32,United-States,<=50K
1,59,Self-emp-not-inc,39774,HS-grad,9,Divorced,Exec-managerial,Unmarried,White,Male,11,0,32,United-States,<=50K
2,25,Self-emp-not-inc,198544,Some-college,10,Never-married,Craft-repair,Own-child,White,Male,3,0,48,United-States,<=50K
3,32,Federal-gov,174991,Some-college,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
4,26,Private,407917,Some-college,10,Never-married,Prof-specialty,Not-in-family,Black,Male,19,0,49,Columbia,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,39,Private,214899,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,15039,0,49,United-States,>50K
96,20,Private,174055,Bachelors,13,Never-married,Sales,Not-in-family,White,Female,0,0,45,United-States,<=50K
97,36,Local-gov,184788,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Male,22,0,32,United-States,<=50K
98,31,Private,284943,HS-grad,9,Married-civ-spouse,Other-service,Wife,White,Female,7697,0,40,United-States,<=50K
99,24,Self-emp-not-inc,388861,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,29,0,48,?,<=50K

In [16]:
from sdv.datasets.demo import get_available_demos

get_available_demos(modality='multi_table')

          dataset_name   size_MB  num_tables
0            Accidents  1029.070           3
1      Atherosclerosis     7.220           4
2   AustralianFootball    57.799           4
3     Biodegradability     4.414           5
4                 Bupa     0.204           9
..                 ...       ...         ...
56            restbase     3.573           3
57             synthea  1755.797          18
58              trains     0.024           2
59          university     0.013           5
60               world     1.266           3

[61 rows x 3 columns]

In [22]:
from sdv.multi_table import HMASynthesizer #import MultiTableSynthesizer

real_data, metadata = download_demo(
  'multi_table', 'world')

synthesizer = HMASynthesizer(metadata, locales=['es-MX', 'en-US'])
synthesizer.fit(real_data)

synthetic_data = synthesizer.sample()

synthetic_data

Preprocess Tables: 100%|██████████| 3/3 [00:00<00:00,  3.55it/s]

Learning relationships:

(1/2) Tables 'Country' and 'City' ('CountryCode'): 100%|██████████| 232/232 [00:03<00:00, 63.99it/s]
(2/2) Tables 'Country' and 'CountryLanguage' ('CountryCode'): 100%|██████████| 233/233 [00:03<00:00, 63.96it/s]

Modeling Tables: 100%|██████████| 3/3 [00:01<00:00,  1.76it/s]

{'Country':       Code                                   Name      Continent  \
 0    AAACf                                Vietnam           Asia
 1    AAADl                             East Timor         Europe
 2    AAABY                                Denmark           Asia
 3    AAACR                            Switzerland           Asia
 4    AAAEK  Congo, The Democratic Republic of the         Europe
 ..     ...                                    ...            ...
 234  AAACk                                Estonia  South America
 235  AAAEM                     Russian Federation        Oceania
 236  AAAEe                                Senegal  North America
 237  AAACF                               Anguilla         Africa
 238  AAAEB                               Colombia  North America

               Region  SurfaceArea  IndepYear  Population  LifeExpectancy  \
 0     Western Europe      10035.7        NaN     7793266             NaN
 1      North America      17476.3     1940.0      709815            76.1
 2        Middle East      55872.7     1940.0     1009147            54.9
 3    Southern Europe      13775.4        NaN     2320118            82.5
 4     Eastern Europe       8878.9     1378.0      161896            83.1
 ..               ...          ...        ...         ...             ...
 234   Eastern Europe     894979.8     1880.0    46325642            57.6
 235   Southeast Asia      81341.6     1969.0    24518787            81.3
 236    South America          5.6     1945.0     1794915            69.7
 237  Central America    4204899.0     1944.0   141360495            60.6
 238        Caribbean     284530.9     1982.0     2258330            63.6

           GNP     GNPOld         LocalName  \
 0       320.9   153619.0           Vanuatu
 1      1592.2   235135.0       Timor Timur
 2       971.5     8220.0   Djibouti/Jibuti
 3    103771.1   547698.0            Canada
 4         2.3    14279.0  The Cook Islands
 ..        ...        ...               ...
 234    1340.8    60887.0             Ertra
 235      53.3  2035994.0           Réunion
 236  106651.7   448862.0          As-Sudan
 237  295688.7        NaN         Shqipëria
 238    1005.9        NaN    Komori/Comores

                           GovernmentForm                        HeadOfState  \
 0                        Part of Denmark                        Štipe Mesic
 1                               Republic                   Vladimir Voronin
 2                             Federation           Alfonso Portillo Cabrera
 3                               Republic                       Elisabeth II
 4                Administrated by the UN                     Rexhep Mejdani
 ..                                   ...                                ...
 234                     Federal Republic  Miguel Ángel Rodríguez Echeverría
 235                             Republic                           Harald V
 236              Constitutional Monarchy          Valentin Paniagua Corazao
 237                             Republic                       Elisabeth II
 238  Nonmetropolitan Territory of France                       Elisabeth II

      Capital Code2
 0     3251.0    VN
 1     4065.0    TO
 2     2704.0    DM
 3        2.0    CC
 4     2436.0    CD
 ..       ...   ...
 234   2534.0    EH
 235   3591.0    SA
 236   2184.0    SD
 237      1.0    AI
 238   1033.0    KM

 [239 rows x 15 columns],
 'City':             ID                Name CountryCode      District  Population
 0     14833870              Biskra       AAACR        Béchar          42
 1     15610536              Huambo       AAACR         Kabol       53565
 2      7773204          Maastricht       AAACR       Utrecht       93560
 3      3008411  Tlemcen (Tilimsen)       AAACR         Kabol      256004
 4     10975503               Lanús       AAACR    Gelderland          42
 ...        ...                 ...         ...           ...         ...
 4074   8946412              Malang       AAAEB       Gauteng          42
 4075   6363948         East London       AAAEB      al-Minya       95852
 4076    356848           Koronadal       AAAEB   La Libertad          42
 4077   1062934         Muzaffarpur       AAAEB  Puerto Plata      279291
 4078   4902054            Bilaspur       AAAEB     West Java          42

 [4079 rows x 5 columns],
 'CountryLanguage':     CountryCode_Language CountryCode     Language IsOfficial  Percentage
 0                  AAAAB       AAACf       Rwanda          F         0.0
 1                  AAAAA       AAACf       Ketšua          T        19.6
 2                  AAAAC       AAADl     Javanese          F         3.9
 3                  AAAAD       AAABY        Tamil          F         0.0
 4                  AAAAE       AAABY      Kurdish          F        45.2
 ..                   ...         ...          ...        ...         ...
 979                AAASl       AAACF    Hungarian          F        31.4
 980                AAASr       AAACF  Belorussian          F        15.6
 981                AAASv       AAAEB        Dutch          F         0.0
 982                AAASu       AAAEB      Balochi          F         0.0
 983                AAASt       AAAEB      English          F        13.4

 [984 rows x 5 columns]}

In [ ]:
from sdv.datasets.demo import get_available_demos

get_available_demos(modality='sequential')

Citations

- https://docs.sdv.dev/sdv/integration/utils/demo
- https://blog.kubeflow.org/kfp/2025/02/16/synthetic-data-using-kfp.html
- https://datacebo.com/sdv-dev/